sudo docker pull nginx
sudo docker pull node
sudo docker pull redis
sudo docker pull postgres
sudo docker pull mongo
sudo docker pull mysql
sudo docker pull localstack/localstack
sudo docker pull jenkins/jenkins
sudo docker pull couchbase
sudo docker pull mariadb
sudo docker pull rabbitmq
sudo docker pull php
sudo docker pull sonarqube
sudo docker pull ruby
sudo docker pull amazonlinux
sudo docker pull maven
sudo docker pull vault
sudo docker pull bash
sudo docker pull mongo-express
sudo docker pull gradle
sudo docker pull cassandra
sudo docker pull kibana
sudo docker pull groovy
sudo docker pull owncloud/server
sudo docker pull rust
sudo docker pull teamspeak
sudo docker pull websphere-libery
sudo docker pull swift
sudo docker pull postfixadmin
sudo docker pull swipl
sudo docker pull emqx
sudo docker pull api-firewall
sudo docker pull google/cloud-sdk
sudo docker pull amazon/dynamodb-local
sudo docker pull amazon/aws-cli
sudo docker pull gitlab/gitlab-ce
