sudo docker pull nginx
sudo docker pull node
sudo docker pull redis
sudo docker pull postgres
sudo docker pull mongo
sudo docker pull mysql
sudo docker pull localstack/localstack
sudo docker pull jenkins/jenkins
sudo docker pull couchbase
